source:         .
destination:    ./_site

base_url:       http://kevin.triageworks.net
description:    "The Projects and Musings of Kevin Richardson"

exclude:        [newpost.sh, Rakefile, README.md, .git/]
