source:         .
destination:    ./_site

base_url:       http://kevin.magically.us
url:            http://kevin.magically.us
description:    "The Projects and Musings of Kevin Richardson"

exclude:        [Rakefile, README.md, .git/]
