<?php

/** ----------------------------------
/   creates MWS files, etc
/   K. Richardson <borismalcov@users.sf.net>
/   ----------------------------------
**/

// creates a magic workstation .mwDeck file from an array of card ids
function createMWDeck($cards)
{
	// connect to the sqlite database
	global $base;

	// generate a name for the deck
	$deck_name = time() . ".mwDeck";

	// make the browser interpret this as a download
	header("Content-type: application/octet-stream");
	header("Content-Disposition: attachment; filename=\"$deck_name\"");

	$to_print = "// Deck file for Magic Workstation (http://www.magicworkstation.com)\n";
	$to_print .= "// Generated by a Nifty Sealed Script\n\n";

	// put all the cards in the SB so people can easily add
	// them to their deck
	$to_print .= "// Sideboard\n";

	foreach($cards as $card)
	{
		$query = "SELECT * FROM cards WHERE id=$card";
		
        	// query the database and print out the names, etc
	        $results = $base->query($query);
        	while($row = $results->fetchArray()) {
                	// $row[1] is the set id & $row[2] is the name
                	$to_print .= "SB: 1 ";

	                // get the set code
        	        $set_code = $base->querySingle("SELECT code FROM sets WHERE id=" . $row[1]);

                	$to_print .= "[$set_code] $row[2]\n";
        	}

	}

	// close the SQLite DB connection
	$base->close();

	// return the file to the user
	print($to_print);
}

?>
